package ics

import (
	"errors"
	"fmt"
	"time"
)

// OriginKind identifies why an instance exists in the expansion.
type OriginKind string

const (
	// OriginStart is the single original occurrence defined by DTSTART.
	OriginStart OriginKind = "DTSTART"
	// OriginRRule is an occurrence generated by an RRULE.
	OriginRRule OriginKind = "RRULE"
	// OriginRDate is an occurrence injected by an RDATE.
	OriginRDate OriginKind = "RDATE"
)

// SourceKind categorizes a single piece of evidence for an instance.
type SourceKind string

const (
	// SourceStart marks the DTSTART occurrence.
	SourceStart SourceKind = "DTSTART"
	// SourceRRule marks generation by an RRULE (indexed by rule order).
	SourceRRule SourceKind = "RRULE"
	// SourceRDate marks injection by an RDATE value.
	SourceRDate SourceKind = "RDATE"
	// SourceExclusion marks removal by an EXDATE (only present in diagnostics).
	SourceExclusion SourceKind = "EXDATE"
	// SourceExRule marks removal by an EXRULE (only present in diagnostics).
	SourceExRule SourceKind = "EXRULE"
	// SourceOverride marks a RECURRENCE-ID override component.
	SourceOverride SourceKind = "RECURRENCE-ID"
)

// Source is one piece of provenance explaining why an occurrence exists or
// was removed. Multiple sources attached to the same instant are merged.
type Source struct {
	Kind SourceKind
	// RuleIndex is the zero-based position among the event's RRULE/EXRULE
	// properties; zero for DTSTART/RDATE/EXDATE/override sources.
	RuleIndex int
	// Value is the raw property value (e.g. "20240310T130000Z") for debugging.
	Value string
}

// Override describes a RECURRENCE-ID override VEVENT.
type Override struct {
	// Component is the overriding VEVENT (carries DTSTART, SUMMARY changes,
	// CANCELLED status, etc.).
	Component *VEvent
	// RecurrenceID is the parsed RECURRENCE-ID value.
	RecurrenceID DateTime
	// NewStart is the override's DTSTART. It differs from the occurrence the
	// override targets when the instance was rescheduled.
	NewStart DateTime
	// Cancelled is true when the override has STATUS:CANCELLED.
	Cancelled bool
	// Orphan is true when the RECURRENCE-ID does not match any occurrence the
	// master generates; the override is then emitted as its own instance.
	Orphan bool
}

// Instance is one expanded occurrence within the requested window.
type Instance struct {
	// Start is the occurrence start with its original time semantics.
	Start DateTime
	// End is the occurrence end (DTEND offset applied to the occurrence, or
	// DURATION); it mirrors Start's kind. Zero when no end is defined.
	End DateTime
	// Sources lists every origin that produced this instant (DTSTART, one or
	// more RRULEs, RDATE), sorted for stable output.
	Sources []Source
	// Override points to the RECURRENCE-ID component that replaces this
	// occurrence; nil when the master definition applies.
	Override *Override
	// Suppressed is true when a CANCELLED override removes the occurrence.
	// Suppressed instances are excluded from the normal iteration; they appear
	// in Result.Diagnostics when diagnostics are enabled.
	Suppressed bool
}

// ExcludedRecord is an occurrence that a rule/RDATE would have produced but
// which an EXDATE, EXRULE or CANCELLED RECURRENCE-ID removed. Records are only
// populated with diagnostics enabled and never participate in normal output.
type ExcludedRecord struct {
	Start   DateTime
	Reasons []Source
}

// Diagnostics collects evidence that does not belong in the normal instance
// iteration.
type Diagnostics struct {
	// Excluded lists every removed occurrence within the window.
	Excluded []ExcludedRecord
	// UnknownTimezones lists TZID values that could not be resolved. Events
	// using them fail expansion; the list aids error messages.
	UnknownTimezones []string
}

// Result is the outcome of expanding one event (a master VEVENT plus its
// RECURRENCE-ID overrides) over a window.
type Result struct {
	// Instances is sorted ascending by instant (floating values by wall clock)
	// and contains only surviving occurrences inside the window.
	Instances []*Instance
	// Truncated is true when expansion stopped because MaxInstances was hit.
	// When true, Instances is incomplete and callers must not treat the end as
	// a natural rule termination.
	Truncated bool
	// Truncation distinguishes the reason Truncated is set.
	Truncation TruncationReason
	// Diagnostics is populated only when requested.
	Diagnostics Diagnostics
}

// TruncationReason distinguishes "hit the caller's cap" from engine safety
// limits.
type TruncationReason string

const (
	TruncationNone TruncationReason = ""
	// TruncationMaxInstances means MaxInstances in-window instances were found
	// and the engine stopped on purpose.
	TruncationMaxInstances TruncationReason = "MAX_INSTANCES"
	// TruncationSafetyLimit means an internal candidate scan limit was hit,
	// indicating an extremely complex or hostile rule.
	TruncationSafetyLimit TruncationReason = "SAFETY_LIMIT"
)

// Sentinel errors returned by the expansion API.
var (
	// ErrExpansionTruncated wraps results that stopped because MaxInstances was
	// reached. Use errors.Is to detect it; the partial Result is still usable.
	ErrExpansionTruncated = errors.New("event expansion truncated at MaxInstances")
	// ErrNoStart reports a master VEVENT without a DTSTART.
	ErrNoStart = errors.New("cannot expand VEVENT without DTSTART")
)

// ExpandOption configures opt-in event expansion.
type ExpandOption func(*expandConfig)

type expandConfig struct {
	diagnostics bool
	resolvers   []TimezoneResolver
	// floatingLocation hosts floating (and date-only) wall clocks. It must be
	// fixed-offset so results never depend on the host's local zone.
	floatingLocation   *time.Location
	windowInclusiveEnd bool
	includeSuppressed  bool
}

// WithDiagnostics enables population of Result.Diagnostics (excluded
// occurrences and unresolved TZIDs). It does not change Instances.
func WithDiagnostics() ExpandOption {
	return func(c *expandConfig) { c.diagnostics = true }
}

// WithTimezoneResolvers appends resolvers tried (in order) when a TZID is not
// covered by an embedded VTIMEZONE. Resolvers run before the host IANA
// database; return nil to decline.
func WithTimezoneResolvers(resolvers ...TimezoneResolver) ExpandOption {
	return func(c *expandConfig) { c.resolvers = append(c.resolvers, resolvers...) }
}

// WithFloatingLocation sets the fixed-offset location used for floating times.
// Defaults to a synthetic UTC+0 zone named "FLOATING", never time.Local.
func WithFloatingLocation(loc *time.Location) ExpandOption {
	return func(c *expandConfig) { c.floatingLocation = loc }
}

// WithInclusiveWindowEnd makes the window closed on both ends. The default is
// half-open: [WindowStart, WindowEnd).
func WithInclusiveWindowEnd() ExpandOption {
	return func(c *expandConfig) { c.windowInclusiveEnd = true }
}

// defaultFloatingZone is a dedicated fixed zone for floating times. It
// deliberately is not time.Local, so host settings can never influence
// output.
var defaultFloatingZone = time.FixedZone("FLOATING", 0)

// ExpandEvent expands a single master VEVENT into its instances over window
// [windowStart, windowEnd). overrides are sibling VEVENTs with the same UID
// carrying RECURRENCE-ID; pass nil to resolve them from an empty set. maxInstances
// is a hard, positive cap on returned instances that protects against unbounded
// rules. opts are the same ParseOption/TimezoneMapper style options accepted by
// the parser, plus the expansion-specific With* options.
//
// On truncation the returned Result has Truncated set and the returned error
// satisfies errors.Is(err, ErrExpansionTruncated); the partial result is still
// returned.
func ExpandEvent(master *VEvent, windowStart, windowEnd time.Time, maxInstances int, overrides []*VEvent, opts ...any) (*Result, error) {
	if master == nil {
		return nil, fmt.Errorf("expand: nil master event")
	}
	if maxInstances <= 0 {
		return nil, fmt.Errorf("expand: maxInstances must be positive")
	}
	if !windowEnd.After(windowStart) {
		return nil, fmt.Errorf("expand: window end must be after window start")
	}
	cfg := &expandConfig{floatingLocation: defaultFloatingZone}
	var parseOpts []any
	for _, opt := range opts {
		if eo, ok := opt.(ExpandOption); ok {
			eo(cfg)
			continue
		}
		parseOpts = append(parseOpts, opt)
	}
	eng, err := newExpander(master, overrides, cfg, parseOpts)
	if err != nil {
		return nil, err
	}
	return eng.expand(windowStart.UTC(), windowEnd.UTC(), maxInstances)
}

// internal engine -----------------------------------------------------------

type expander struct {
	cfg       *expandConfig
	master    *VEvent
	start     DateTime
	end       DateTime
	hasEnd    bool
	rules     []*RecurrenceRule
	ruleVals  []string
	rdate     []DateTime
	rdateVal  []string
	exdate    []DateTime
	exdateVal []string
	exrules   []*RecurrenceRule
	overrides map[string]*Override
	floating  *time.Location
	locCache  map[string]*time.Location
}

func newExpander(master *VEvent, overrides []*VEvent, cfg *expandConfig, parseOpts []any) (*expander, error) {
	startProp := master.GetProperty(ComponentPropertyDtStart)
	if startProp == nil {
		return nil, ErrNoStart
	}
	e := &expander{
		cfg:       cfg,
		master:    master,
		overrides: map[string]*Override{},
		locCache:  map[string]*time.Location{},
		floating:  cfg.floatingLocation,
	}
	if e.floating == nil {
		e.floating = defaultFloatingZone
	}
	var err error
	e.start, err = e.parseDateTime(startProp)
	if err != nil {
		return nil, fmt.Errorf("expand DTSTART: %w", err)
	}
	if endProp := master.GetProperty(ComponentPropertyDtEnd); endProp != nil {
		e.end, err = e.parseDateTime(endProp)
		if err != nil {
			return nil, fmt.Errorf("expand DTEND: %w", err)
		}
		e.hasEnd = true
	}
	e.rules, e.ruleVals, err = e.readRules(ComponentPropertyRrule)
	if err != nil {
		return nil, err
	}
	exr, exrVals, err := e.readRules(ComponentPropertyExrule)
	if err != nil {
		return nil, err
	}
	_ = exrVals
	e.exrules = exr
	e.rdate, e.rdateVal, err = e.readDateList(ComponentPropertyRdate)
	if err != nil {
		return nil, err
	}
	e.exdate, _, err = e.readDateList(ComponentPropertyExdate)
	if err != nil {
		return nil, err
	}
	if err := e.indexOverrides(overrides); err != nil {
		return nil, err
	}
	return e, nil
}
