package ics

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

var errCalendarNil = fmt.Errorf("calendar is nil")

// This file implements the opt-in VEVENT occurrence expansion API.
//
// The expansion machinery is additive: it does not change any existing
// component parsing, serialization, or read/write behaviour. Callers opt in by
// using ExpandEvent / ExpandCalendar explicitly.
//
// Design notes
//
// Every generated occurrence carries the temporal "shape" of its source value:
// a TZID value keeps its IANA identifier and local wall clock, a UTC value keeps
// its Z semantics, a floating value keeps its floating semantics, and a date
// value keeps its all-day semantics. Values are never folded through the host's
// time.Local before comparisons, which makes results independent of the host's
// default time zone.

// InstanceSourceKind identifies why an instance exists.
type InstanceSourceKind string

const (
	// SourceDTStart marks the original DTSTART instance of the recurrence set.
	SourceDTStart InstanceSourceKind = "DTSTART"
	// SourceRRULE marks an instance generated by an RRULE. The zero based
	// RuleIndex identifies which RRULE property produced it.
	SourceRRULE InstanceSourceKind = "RRULE"
	// SourceRDATE marks an instance injected by an RDATE property.
	SourceRDATE InstanceSourceKind = "RDATE"
	// SourceRECURRENCEID marks an override VEVENT (RECURRENCE-ID) that replaced
	// the instance generated from the master event.
	SourceRECURRENCEID InstanceSourceKind = "RECURRENCE-ID"
)

// InstanceSource is one piece of evidence explaining why an instance exists.
// When two rules (or DTSTART and a rule) generate the same instant the sources
// are merged onto a single Instance instead of emitting duplicates.
type InstanceSource struct {
	// Kind is the property category that produced this source.
	Kind InstanceSourceKind
	// RuleIndex is the RRULE property index (zero based, in document order)
	// when Kind is SourceRRULE. It is -1 otherwise.
	RuleIndex int
	// Sequence is the zero based ordinal of the occurrence within a single
	// RRULE stream (DTSTART is sequence 0). Two occurrences that collapse onto
	// the same wall clock during a DST fallback each retain their own sequence.
	Sequence int
}

// TimeKind describes how a time value was expressed in the source data.
type TimeKind string

const (
	// TimeKindUTC is a UTC time ("...Z").
	TimeKindUTC TimeKind = "UTC"
	// TimeKindTZID is a local time referenced by a TZID parameter.
	TimeKindTZID TimeKind = "TZID"
	// TimeKindFloating is a local time with no TZID and no Z suffix.
	TimeKindFloating TimeKind = "FLOATING"
	// TimeKindDate is a date-only VALUE=DATE (all-day) occurrence.
	TimeKindDate TimeKind = "DATE"
)

// TimeValue is a time value that preserves its original iCalendar semantics.
//
// Time is an absolute instant usable for ordering and window comparisons:
//   - UTC values are parsed as UTC;
//   - TZID values are interpreted in their named location;
//   - floating values are interpreted deterministically in the location given
//     by WithFloatingLocation (UTC by default), never time.Local;
//   - date values are midnight UTC.
//
// The wall clock fields and TZID/Kind metadata let callers render the value the
// same way the source expressed it.
type TimeValue struct {
	// Time is the absolute instant.
	Time time.Time
	// Kind is the temporal kind of the source value.
	Kind TimeKind
	// TZID is the TZID parameter value when Kind is TimeKindTZID.
	TZID string
	// DateOnly is true when the source value was VALUE=DATE.
	DateOnly bool
	// Wall is the local wall clock as written in the source data. It carries no
	// zone offset and is intended for display/reconstruction, not comparison.
	Wall time.Time
}

// IsFloating reports whether the value is a floating local time.
func (tv TimeValue) IsFloating() bool { return tv.Kind == TimeKindFloating }

// instanceKey identifies an occurrence for merging/exclusion purposes.
// Same instant values collapse; DST fallback occurrences that share a wall
// clock but differ in offset are distinguished by ZoneOffset.
type instanceKey struct {
	unix       int64
	date       bool
	tzid       string
	kind       TimeKind
	zoneOffset int
}

func (tv TimeValue) key() instanceKey {
	k := instanceKey{unix: tv.Time.UnixNano(), kind: tv.Kind, tzid: tv.TZID, date: tv.DateOnly}
	if tv.Kind == TimeKindTZID {
		_, k.zoneOffset = tv.Time.Zone()
	}
	return k
}

// OverrideRange mirrors the RECURRENCE-ID RANGE parameter.
type OverrideRange string

const (
	// OverrideRangeSingle replaces only the matching instance (RANGE absent).
	OverrideRangeSingle OverrideRange = ""
	// OverrideRangeThisAndPrior replaces the matching instance and all earlier
	// instances (RANGE=THISANDPRIOR, deprecated but accepted).
	OverrideRangeThisAndPrior OverrideRange = "THISANDPRIOR"
	// OverrideRangeThisAndFuture replaces the matching instance and all later
	// instances (RANGE=THISANDFUTURE).
	OverrideRangeThisAndFuture OverrideRange = "THISANDFUTURE"
)

// OverrideInfo links a generated instance to the VEVENT override that replaced
// it (the VEVENT carrying RECURRENCE-ID).
type OverrideInfo struct {
	// Event is the override VEVENT.
	Event *VEvent
	// RecurrenceID is the RECURRENCE-ID value identifying the replaced slot.
	RecurrenceID TimeValue
	// Range is the RANGE parameter (if any).
	Range OverrideRange
	// Cancelled is true when the override has STATUS:CANCELLED: the slot is
	// removed from Instances and reported in Excluded instead.
	Cancelled bool
}

// Instance is one expanded occurrence.
type Instance struct {
	// Start is the occurrence start with preserved semantics.
	Start TimeValue
	// End is the occurrence end with preserved semantics. It is the zero
	// TimeValue when the master (and override) defines neither DTEND nor
	// DURATION.
	End TimeValue
	// Sources is the ordered, de-duplicated evidence explaining why the
	// instance exists (e.g. DTSTART + RRULE, or RRULE from two RRULEs).
	Sources []InstanceSource
	// Override is present when a RECURRENCE-ID VEVENT replaces this instance.
	Override *OverrideInfo
	// Event is the master VEVENT the instance was generated from (or the
	// override VEVENT when Override is present).
	Event *VEvent
}

// ExcludeReason categorizes an item that is present in the raw recurrence set
// but absent from Instances.
type ExcludeReason string

const (
	// ExcludedByEXDATE marks removal by an EXDATE property.
	ExcludedByEXDATE ExcludeReason = "EXDATE"
	// ExcludedByEXRULE marks removal by an EXRULE property.
	ExcludedByEXRULE ExcludeReason = "EXRULE"
	// ExcludedByCancellation marks removal by a STATUS:CANCELLED RECURRENCE-ID.
	ExcludedByCancellation ExcludeReason = "CANCELLED"
)

// ExcludedInstance is an occurrence that was removed from Instances. It is only
// populated in diagnostic mode (WithDiagnostics) and never mixes into normal
// iteration.
type ExcludedInstance struct {
	// Start is the removed occurrence.
	Start TimeValue
	// Reason is why it was removed.
	Reason ExcludeReason
	// Sources is the evidence the occurrence had before removal.
	Sources []InstanceSource
}

// TruncatedReason distinguishes a natural end from a forced cut-off.
type TruncatedReason string

const (
	// NotTruncated means the recurrence set ended naturally (COUNT/UNTIL or a
	// finite rule) or the window simply ended first.
	NotTruncated TruncatedReason = ""
	// TruncatedMaxInstances means MaxInstances was reached while more in-window
	// instances existed.
	TruncatedMaxInstances TruncatedReason = "MAX_INSTANCES"
	// TruncatedBudget means the expansion safety budget was exhausted while the
	// rule still appeared productive (defensive guard against pathological
	// rules). It also indicates the output is incomplete.
	TruncatedBudget TruncatedReason = "BUDGET"
)

// ExpansionResult is the output of expanding one master VEVENT.
type ExpansionResult struct {
	// UID is the master event UID.
	UID string
	// Master is the master VEVENT.
	Master *VEvent
	// Instances are the surviving occurrences sorted by instant, then by
	// semantic key, with de-duplicated sources.
	Instances []Instance
	// Excluded contains removed occurrences, populated only with
	// WithDiagnostics.
	Excluded []ExcludedInstance
	// OrphanOverrides lists RECURRENCE-ID events that did not match any
	// generated instance in the window. Populated in diagnostic mode only.
	OrphanOverrides []OverrideInfo
	// Truncated reports whether (and why) expansion stopped before a natural
	// end. NotTruncated means complete relative to the window.
	Truncated TruncatedReason
}

// Window is the half-open expansion interval [From, To) by default.
type Window struct {
	// From is the inclusive lower bound. The zero time means unbounded past.
	From time.Time
	// To is the exclusive upper bound. The zero time means unbounded future.
	To time.Time
	// IncludeTo makes To inclusive when true.
	IncludeTo bool
}

func (w Window) contains(t time.Time) bool {
	if !w.From.IsZero() && t.Before(w.From) {
		return false
	}
	if !w.To.IsZero() {
		if w.pastEnd(t) {
			return false
		}
	}
	return true
}

// pastEnd reports whether t is beyond the window's upper bound according to
// its inclusivity.
func (w Window) pastEnd(t time.Time) bool {
	if w.To.IsZero() {
		return false
	}
	if w.IncludeTo {
		return t.After(w.To)
	}
	return !t.Before(w.To)
}

// DefaultMaxInstances caps an expansion when the caller passes MaxInstances<=0.
const DefaultMaxInstances = 1000

// expansionConfig holds resolved opt-in options.
type expansionConfig struct {
	window         Window
	maxInstances   int
	diagnostics    bool
	timezoneMapper TimezoneMapper
	floatingLoc    *time.Location
	includeExRules bool
	overrideEvents []*VEvent
	overrideList   []OverrideInfo
}

func defaultExpansionConfig() *expansionConfig {
	return &expansionConfig{
		maxInstances:   DefaultMaxInstances,
		floatingLoc:    time.UTC,
		includeExRules: true,
	}
}

// ExpandOption configures event expansion.
type ExpandOption func(*expansionConfig) error

// WithWindow sets the expansion window. The default is an unbounded window, so
// callers should always pass one for unbounded rules.
func WithWindow(w Window) ExpandOption {
	return func(c *expansionConfig) error {
		if !w.From.IsZero() && !w.To.IsZero() && w.To.Before(w.From) {
			return fmt.Errorf("expand window To %s is before From %s", w.To, w.From)
		}
		c.window = w
		return nil
	}
}

// WithMaxInstances caps the number of instances returned. Values <= 0 select
// DefaultMaxInstances. When the cap is hit the result is returned with
// Truncated == TruncatedMaxInstances instead of pretending the rule ended.
func WithMaxInstances(n int) ExpandOption {
	return func(c *expansionConfig) error {
		if n <= 0 {
			n = DefaultMaxInstances
		}
		c.maxInstances = n
		return nil
	}
}

// WithDiagnostics enables population of ExpansionResult.Excluded and
// OrphanOverrides. Excluded items never appear in Instances regardless of this
// option.
func WithDiagnostics() ExpandOption {
	return func(c *expansionConfig) error {
		c.diagnostics = true
		return nil
	}
}

// WithExpandTimezoneMapper supplies a resolver for TZID values that the host's
// tzdata cannot load (for example VTIMEZONE-derived or custom identifiers). It
// is consulted before time.LoadLocation.
func WithExpandTimezoneMapper(m TimezoneMapper) ExpandOption {
	return func(c *expansionConfig) error {
		c.timezoneMapper = m
		return nil
	}
}

// WithFloatingLocation sets the deterministic location used to turn floating
// (no TZID, no Z) values into comparable instants. The default is UTC, so host
// time.Local never influences results.
func WithFloatingLocation(loc *time.Location) ExpandOption {
	return func(c *expansionConfig) error {
		if loc == nil {
			return fmt.Errorf("floating location is nil")
		}
		c.floatingLoc = loc
		return nil
	}
}

// WithExRulesIncluded controls whether deprecated EXRULE properties remove
// instances. They are honored by default; pass false to ignore them.
func WithExRulesIncluded(include bool) ExpandOption {
	return func(c *expansionConfig) error {
		c.includeExRules = include
		return nil
	}
}

// WithOverrides supplies RECURRENCE-ID VEVENTs that modify instances of the
// master event. ExpandCalendar groups overrides by UID automatically; this
// option is for callers expanding a single master directly.
func WithOverrides(overrides ...*VEvent) ExpandOption {
	return func(c *expansionConfig) error {
		c.overrideEvents = append(c.overrideEvents, overrides...)
		return nil
	}
}

// ExpansionError wraps an expansion failure with a stable category.
type ExpansionError struct {
	// Op identifies the failing stage, e.g. "dtstart", "rrule", "tzid".
	Op string
	// Err is the underlying error.
	Err error
}

func (e *ExpansionError) Error() string {
	if e == nil {
		return "expansion error"
	}
	return fmt.Sprintf("expand %s: %v", e.Op, e.Err)
}

func (e *ExpansionError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Err
}

func expansionError(op string, err error) error {
	if err == nil {
		return nil
	}
	return &ExpansionError{Op: op, Err: err}
}

// parseTimeValueTyped parses one iCal time value preserving its semantic kind.
// params is the property parameter map (for TZID and VALUE).
func (cfg *expansionConfig) parseTimeValueTyped(raw string, params map[string][]string) (TimeValue, error) {
	raw = strings.TrimSpace(raw)
	matched := timeStampVariations.FindStringSubmatch(raw)
	if matched == nil {
		return TimeValue{}, fmt.Errorf("%w, got %q", ErrTimeValueNotMatched, raw)
	}

	isDate := len(matched[1]) > 0 && len(matched[3]) == 0 && matched[2] != "T"
	if vals, ok := params[string(ParameterValue)]; ok {
		for _, v := range vals {
			if v == string(ValueDataTypeDate) {
				isDate = true
			}
		}
	}

	tzid := ""
	if vals, ok := params[string(ParameterTzid)]; ok && len(vals) == 1 {
		tzid = vals[0]
	}

	switch {
	case isDate:
		wall, err := time.Parse(icalDateFormatLocal, matched[1])
		if err != nil {
			return TimeValue{}, err
		}
		return TimeValue{Time: wall.UTC(), Kind: TimeKindDate, DateOnly: true, Wall: wall}, nil
	case matched[4] == "Z":
		t, err := time.ParseInLocation(icalTimestampFormatUtc, raw, time.UTC)
		if err != nil {
			return TimeValue{}, err
		}
		return TimeValue{Time: t, Kind: TimeKindUTC, Wall: t}, nil
	case tzid != "":
		loc, err := cfg.resolveTZID(tzid)
		if err != nil {
			return TimeValue{}, err
		}
		wall, err := time.Parse(icalTimestampFormatLocal, matched[1]+"T"+matched[3])
		if err != nil {
			return TimeValue{}, err
		}
		t := time.Date(wall.Year(), wall.Month(), wall.Day(), wall.Hour(), wall.Minute(), wall.Second(), 0, loc)
		return TimeValue{Time: t, Kind: TimeKindTZID, TZID: tzid, Wall: wall}, nil
	default:
		wall, err := time.Parse(icalTimestampFormatLocal, matched[1]+"T"+matched[3])
		if err != nil {
			return TimeValue{}, err
		}
		t := time.Date(wall.Year(), wall.Month(), wall.Day(), wall.Hour(), wall.Minute(), wall.Second(), 0, cfg.floatingLoc)
		return TimeValue{Time: t, Kind: TimeKindFloating, Wall: wall}, nil
	}
}

func (cfg *expansionConfig) resolveTZID(tzid string) (*time.Location, error) {
	if cfg.timezoneMapper != nil {
		if loc := cfg.timezoneMapper(tzid); loc != nil {
			return loc, nil
		}
	}
	loc, err := time.LoadLocation(tzid)
	if err != nil {
		return nil, fmt.Errorf("unknown TZID %q: %w", tzid, err)
	}
	return loc, nil
}

// multiTimeProps parses all values of RDATE/EXDATE properties. RDATE PERIOD
// values (start/end separated by "/") contribute their start instant.
func (cfg *expansionConfig) multiTimeProps(event *VEvent, prop ComponentProperty) ([]TimeValue, error) {
	var out []TimeValue
	for _, p := range event.GetProperties(prop) {
		isPeriod := false
		for _, v := range p.ICalParameters[string(ParameterValue)] {
			if v == "PERIOD" {
				isPeriod = true
			}
		}
		for _, raw := range strings.Split(p.Value, ",") {
			raw = strings.TrimSpace(raw)
			if raw == "" {
				continue
			}
			if isPeriod {
				if i := strings.IndexByte(raw, '/'); i >= 0 {
					raw = raw[:i]
				}
			}
			tv, err := cfg.parseTimeValueTyped(raw, p.ICalParameters)
			if err != nil {
				return nil, err
			}
			out = append(out, tv)
		}
	}
	return out, nil
}

func (cfg *expansionConfig) propTime(event *VEvent, prop ComponentProperty) (TimeValue, bool, error) {
	p := event.GetProperty(prop)
	if p == nil {
		return TimeValue{}, false, nil
	}
	tv, err := cfg.parseTimeValueTyped(p.Value, p.ICalParameters)
	if err != nil {
		return TimeValue{}, false, err
	}
	return tv, true, nil
}

// ExpandEvent expands one master VEVENT into the instances in w.
//
// master must be a recurring or single VEVENT (typically one without a
// RECURRENCE-ID). RECURRENCE-ID overrides are supplied with WithOverrides or by
// using ExpandCalendar, which groups overrides by UID automatically.
func ExpandEvent(master *VEvent, options ...ExpandOption) (*ExpansionResult, error) {
	if master == nil {
		return nil, expansionError("event", fmt.Errorf("master event is nil"))
	}
	cfg := defaultExpansionConfig()
	if mapper := master.getTimezoneMapper(); mapper != nil && cfg.timezoneMapper == nil {
		cfg.timezoneMapper = mapper
	}
	for i, opt := range options {
		if opt == nil {
			return nil, expansionError("options", fmt.Errorf("%w %d: nil option", ErrInvalidOpArg, i))
		}
		if err := opt(cfg); err != nil {
			return nil, expansionError("options", err)
		}
	}
	for i, ovEvent := range cfg.overrideEvents {
		ov, err := cfg.buildOverride(ovEvent)
		if err != nil {
			return nil, expansionError(fmt.Sprintf("override[%d]", i), err)
		}
		cfg.overrideList = append(cfg.overrideList, ov)
	}
	sort.Slice(cfg.overrideList, func(i, j int) bool {
		return cfg.overrideList[i].RecurrenceID.Time.Before(cfg.overrideList[j].RecurrenceID.Time)
	})

	res := &ExpansionResult{Master: master, UID: master.Id()}

	dtstart, hasStart, err := cfg.propTime(master, ComponentPropertyDtStart)
	if err != nil {
		return nil, expansionError("dtstart", err)
	}
	if !hasStart {
		return nil, expansionError("dtstart", ErrPropertyNotFound)
	}

	duration, hasDuration, err := cfg.eventDuration(master, dtstart)
	if err != nil {
		return nil, err
	}

	// merged accumulates occurrences by semantic key.
	merged := map[instanceKey]*Instance{}
	var keyOrder []instanceKey
	addSource := func(tv TimeValue, src InstanceSource) {
		k := tv.key()
		inst, ok := merged[k]
		if !ok {
			inst = &Instance{Start: tv, Event: master}
			if hasDuration {
				inst.End = shiftTimeValue(tv, duration)
			}
			merged[k] = inst
			keyOrder = append(keyOrder, k)
		}
		if !sourcePresent(inst.Sources, src) {
			inst.Sources = append(inst.Sources, src)
		}
	}

	// DTSTART is always the first member of the recurrence set.
	addSource(dtstart, InstanceSource{Kind: SourceDTStart, RuleIndex: -1, Sequence: 0})

	// RRULE streams.
	ruleProps := master.GetProperties(ComponentPropertyRrule)
	ruleTruncated := false
	for i, rp := range ruleProps {
		rule, err := ParseRecurrenceRule(rp.Value)
		if err != nil {
			return nil, expansionError(fmt.Sprintf("rrule[%d]", i), err)
		}
		gen := newRuleGenerator(rule, dtstart, cfg)
		for {
			tv, seq, more, gerr := gen.next()
			if gerr != nil {
				return nil, expansionError(fmt.Sprintf("rrule[%d]", i), gerr)
			}
			if tv.Time.IsZero() == false {
				addSource(tv, InstanceSource{Kind: SourceRRULE, RuleIndex: i, Sequence: seq})
			}
			if !more {
				break
			}
			if gen.truncated {
				res.Truncated = gen.truncReason
				ruleTruncated = true
				break
			}
		}
	}

	// RDATE injections.
	rdates, err := cfg.multiTimeProps(master, ComponentPropertyRdate)
	if err != nil {
		return nil, expansionError("rdate", err)
	}
	for _, tv := range rdates {
		addSource(tv, InstanceSource{Kind: SourceRDATE, RuleIndex: -1})
	}

	// EXDATE / EXRULE removal. Matching semantics:
	//   - DATE matches only DATE;
	//   - UTC and TZID values match by absolute instant across each other;
	//   - floating values match only floating values at the same wall clock.
	var excluded []ExcludedInstance
	remove := func(tv TimeValue, reason ExcludeReason) bool {
		for k, inst := range merged {
			if exclusionMatches(tv, inst.Start) {
				if cfg.diagnostics {
					excluded = append(excluded, ExcludedInstance{Start: inst.Start, Reason: reason, Sources: inst.Sources})
				}
				delete(merged, k)
				return true
			}
		}
		return false
	}

	exdates, err := cfg.multiTimeProps(master, ComponentPropertyExdate)
	if err != nil {
		return nil, expansionError("exdate", err)
	}
	for _, tv := range exdates {
		remove(tv, ExcludedByEXDATE)
	}

	if cfg.includeExRules {
		exRuleProps := master.GetProperties(ComponentPropertyExrule)
		for i, ep := range exRuleProps {
			rule, err := ParseRecurrenceRule(ep.Value)
			if err != nil {
				return nil, expansionError(fmt.Sprintf("exrule[%d]", i), err)
			}
			gen := newRuleGenerator(rule, dtstart, cfg)
			for {
				tv, _, more, gerr := gen.next()
				if gerr != nil {
					return nil, expansionError(fmt.Sprintf("exrule[%d]", i), gerr)
				}
				if !tv.Time.IsZero() {
					remove(tv, ExcludedByEXRULE)
				}
				if !more || gen.truncated {
					break
				}
			}
		}
	}

	// Collect and window-filter the base instances before applying overrides, so
	// that RANGE=THISANDFUTURE overrides observe the ordered recurrence set.
	var bases []Instance
	for _, k := range keyOrder {
		if inst, ok := merged[k]; ok {
			bases = append(bases, *inst)
		}
	}
	sortInstances(bases)

	type pendingCancel struct {
		start TimeValue
		srcs  []InstanceSource
	}
	var pendingCancels []pendingCancel
	matchedOverride := map[int]bool{}

	var kept []Instance
	for _, inst := range bases {
		ovIdx, ov := findOverride(cfg.overrideList, inst.Start)
		inWindow := cfg.window.contains(inst.Start.Time)
		if ovIdx >= 0 {
			matchedOverride[ovIdx] = true
			if ov.Cancelled {
				if inWindow && cfg.diagnostics {
					pendingCancels = append(pendingCancels, pendingCancel{inst.Start, inst.Sources})
				}
				continue
			}
			if inWindow {
				inst.Override = &ov
				inst.Event = ov.Event
				if ns, ok, _ := cfg.propTime(ov.Event, ComponentPropertyDtStart); ok {
					od, hasOd, _ := cfg.eventDuration(ov.Event, ns)
					inst.Start = ns
					if hasOd {
						inst.End = shiftTimeValue(ns, od)
					} else {
						inst.End = TimeValue{}
					}
				} else {
					if od, ok, _ := cfg.eventDuration(ov.Event, inst.Start); ok {
						inst.End = shiftTimeValue(inst.Start, od)
					}
				}
				// A moved override is included iff its new start is in the
				// window (the slot also being in window is guaranteed above).
				if cfg.window.contains(inst.Start.Time) {
					kept = append(kept, inst)
				}
			}
			continue
		}
		// RANGE=THISANDFUTURE / THISANDPRIOR cancelled overrides cover ranges.
		if idx := cancelledRangeIndex(cfg.overrideList, inst.Start); idx >= 0 {
			matchedOverride[idx] = true
			if inWindow && cfg.diagnostics {
				pendingCancels = append(pendingCancels, pendingCancel{inst.Start, inst.Sources})
			}
			continue
		}
		if inWindow {
			kept = append(kept, inst)
		}
	}

	// Overrides may move instances to a new instant; re-sort before capping.
	sortInstances(kept)

	// Stable truncation: enforce the cap and report a distinguishable reason
	// instead of pretending the rule ended naturally.
	if len(kept) > cfg.maxInstances {
		kept = kept[:cfg.maxInstances]
		if res.Truncated == NotTruncated {
			res.Truncated = TruncatedMaxInstances
		}
	} else if len(kept) == cfg.maxInstances && ruleTruncated {
		res.Truncated = TruncatedMaxInstances
	}

	for _, pc := range pendingCancels {
		excluded = append(excluded, ExcludedInstance{Start: pc.start, Reason: ExcludedByCancellation, Sources: pc.srcs})
	}

	res.Instances = kept
	if cfg.diagnostics {
		sort.Slice(excluded, func(i, j int) bool {
			return excluded[i].Start.Time.Before(excluded[j].Start.Time)
		})
		res.Excluded = excluded
		for idx, ov := range cfg.overrideList {
			if !matchedOverride[idx] && cfg.window.contains(ov.RecurrenceID.Time) {
				res.OrphanOverrides = append(res.OrphanOverrides, ov)
			}
		}
		sort.Slice(res.OrphanOverrides, func(i, j int) bool {
			return res.OrphanOverrides[i].RecurrenceID.Time.Before(res.OrphanOverrides[j].RecurrenceID.Time)
		})
	}

	return res, nil
}
